Repository bold-commerce/adobe-commerce-bold-checkout-payment-booster-one-step-checkout-compatibility, pull requests merged in 2025-03, with the labels that each got.

#1 CHK-4747: Create Compatibility Extension for OneStepCheckout
  README.md
  composer.json
  etc/module.xml
  registration.php
  view/frontend/requirejs-config.js
  view/frontend/web/js/action/hide-billing-address.js
  view/frontend/web/js/registration-mixin.js
  view/frontend/web/js/view/billing-address.js
  view/frontend/web/js/view/form/element/email/fastlane-mixin.js
Labels: enhancement

#4 CHK-4747: Add Missing Dependencies
  composer.json
  etc/module.xml
Labels: bug

#3 CHK-4747: Fix Incorrect Extension Name
  etc/module.xml
  registration.php
  view/frontend/requirejs-config.js
  view/frontend/web/js/view/form/element/email/fastlane-mixin.js
Labels: bug

#5 CHK-8104: Create CODEOWNERS
  .github/CODEOWNERS
Labels: infrastructure, developer-experience
